In [10]:
import numpy as np
var1 = np.matrix([[2,2],[2,2]])
var2 = np.matrix([[2,2],[2,2]])
print(var1.dot(var2))
print()
print(var1*var2)

[[8 8]
 [8 8]]

[[8 8]
 [8 8]]


In [18]:
var3 = np.matrix([[1,2,3],[4,5,6]])
print(var3)
print()
print(np.transpose(var3))
print()
print(var3.T)
print()
print(np.swapaxes(var3,1,0))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [19]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.inv(var4))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [25]:
var5 = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(var5,-4))

[[ 39.625  -18.125 ]
 [-27.1875  12.4375]]


In [40]:
var6 = np.array([[[1,2],
                  [3,4]],
                  [[5,6],
                  [7,8]]])
print(var6)
print(np.ndim(var6))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
