In [2]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.47306457 0.76081894 0.59747243 0.17366508]


In [3]:
var1 = np.random.randn(5)
print(var1)

[-1.15208161  1.17929473  1.22075641 -1.22012506 -0.05499308]


In [4]:
 var2 = np.random.ranf(4)
print(var2)

[0.21612848 0.37733687 0.20090066 0.00845968]


In [5]:
var3 = np.random.randint(5,20,5)
print(var3)

[ 8  7 13 11 14]
