In [1]:
import numpy as np
a = np.random.randint(1,5,4)
b = np.random.randint(5,9,4)
print(a)
print(b)
c = a%3
var1 = np.reciprocal(b)
print(c)
print(var1)

[1 4 3 1]
[8 6 7 7]
[1 1 0 1]
[0 0 0 0]


In [2]:

var2 = np.array([[1,2,3,4],[1,2,3,4]])
var3 = np.array([[1,2,3,4],[1,2,3,4]])
var4 = var2 + var3
print(var4)

[[2 4 6 8]
 [2 4 6 8]]
