In [2]:
import numpy as np
var = np.array([[1,2],[1,2]])
print(var)
print()
print(np.shape(var))

[[1 2]
 [1 2]]

(2, 2)


In [6]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [20]:
var2 = np.array([1,2,3,4,5,6])
x = var2.reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


In [23]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x1 = var3.reshape(2,3,2)
print(x1)
one = x1.reshape(-1)
print(one)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
