In [1]:
import numpy as np
var = np.array([1,2,3,4])
co = var.copy()
print(var)
print(co)

[1 2 3 4]
[1 2 3 4]


In [2]:
var2 = np.array([9,8,7,6,5])
vi = var2.view()
print(var2)
print(vi)

[9 8 7 6 5]
[9 8 7 6 5]
