In [5]:
import numpy as np
var  = np.array([1,2,3,4])
print(np.argmin(var), np.argmax(var))

0 3


In [21]:
var2 = np.random.randint(1,5,4)
var3 = np.random.randint(1,5,4)
var4 = np.array([var2,var3])
print(var2)
print(var3)
print(var4)
print(np.sqrt(var3))
print(np.min(var2, axis=0))

[3 4 4 4]
[4 2 1 1]
[[3 4 4 4]
 [4 2 1 1]]
[2.         1.41421356 1.         1.        ]
3


In [28]:
var5 = np.array([0,2,3,5,6,7,8,9,6,5,43,8])
print(np.sin(var5))
print(np.cumsum(var5))

[ 0.          0.90929743  0.14112001 -0.95892427 -0.2794155   0.6569866
  0.98935825  0.41211849 -0.2794155  -0.95892427 -0.83177474  0.98935825]
[  0   2   5  10  16  23  31  40  46  51  94 102]
