In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = arr.reshape(2,3,2)
print(x)
print(x[1,1,0])
print(x.ndim) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
9
3


In [25]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


In [37]:
var3 = np.array([1,2,3,4,5,7,8,9])
print(var3[1::2])


[2 4 7 9]
